FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=development

COPY package.json package-lock.json ./
COPY backend/package.json backend/package.json
COPY frontend/package.json frontend/package.json
COPY shared/package.json shared/package.json

RUN npm ci

COPY frontend frontend
COPY shared shared

EXPOSE 5173

CMD ["npm", "run", "dev", "-w", "@fastik/frontend"]
