FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=development

COPY package.json package-lock.json ./
COPY backend/package.json backend/package.json
COPY frontend/package.json frontend/package.json
COPY shared/package.json shared/package.json

RUN npm ci

COPY backend backend
COPY shared shared

EXPOSE 4200

CMD ["npm", "run", "dev", "-w", "@fastik/backend"]
